#!/bin/bash

set -euo pipefail

echo "Deploying..."
aws s3 sync . s3://koivupuro.com --exclude '*' --include 'css/*' --include 'fonts/*' --include 'index.html' --include 'js/*' --exclude '*/.*' --delete
echo "Finished!"
